/**
 * Pages generated by TypeDoc (`pnpm api:gen`) under src/pages/api, grouped for the sidebar.
 *
 * The files are read as raw text: importing them as modules would be circular, because every
 * API page renders through the Docs layout, which builds this list.
 */
const files = import.meta.glob<string>('../pages/api/**/*.md', { query: '?raw', import: 'default', eager: true });

const GROUPS: [folder: string, title: string][] = [
    ['classes', 'Classes'],
    ['functions', 'Functions'],
    ['interfaces', 'Interfaces'],
    ['types', 'Types'],
    ['type-aliases', 'Types'],
    ['variables', 'Variables'],
];

export interface ApiLink {
    title: string;
    href: string;
    description: string;
    kind: string;
}

/** Reads a single-quoted YAML scalar written by scripts/postprocess-api.mjs. */
function field(raw: string, key: string): string {
    const m = raw.match(new RegExp(`^${key}: '((?:[^']|'')*)'$`, 'm'));

    return m ? m[1].replace(/''/g, "'") : '';
}

let cache: ApiLink[] | null = null;

export function apiPages(): ApiLink[] {
    cache ??= Object.entries(files).map(([file, raw]) => {
        const rel = file.replace('../pages/api/', '').replace(/\.md$/, '');
        const href = rel === 'index' ? '/api/' : `/api/${rel.replace(/\/index$/, '')}/`;

        return { title: field(raw, 'title'), href, description: field(raw, 'description'), kind: rel.split('/')[0] };
    });

    return cache;
}

export function apiNav(): { title: string; items: { label: string; href: string }[] }[] {
    const all = apiPages();

    return [
        { title: 'Reference', items: [{ label: 'Overview', href: '/api/' }] },
        ...GROUPS.map(([folder, title]) => ({
            title,
            items: all
                .filter((p) => p.kind === folder)
                .sort((a, b) => a.title.localeCompare(b.title))
                .map((p) => ({ label: p.title, href: p.href })),
        })).filter((g) => g.items.length > 0),
    ];
}
